name: sayhello
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  cloud_firestore: ^0.8.1+1
  firebase_storage: ^1.0.4
  image_picker: ^0.4.10

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/

